### ISSUE TITLE
Improvement suggestion for the documentation

### ISSUE THREAD

**Issue by ir210** [zkry/awqat#1]
Hi,

Thank you for the package. It's very handy when I don't have my phone nearby.

I have a couple of suggestions to improve the documentation.

I am not sure if it's only on my system, but I need to do the following to make it work.

```emacs-lisp
(setq calendar-latitude 48.093077
      calendar-longitude 11.465853)
```

Both are originally `nil`.

The other thing is that `awqat-prayer-safety-offsets` variable accepts a list of floating point numbers. The documentation gives an impression that they are integers (I am not sure if this is a bug or an overlook in the documentation).

I am a Spacemacs user. To install this package, I only need to put the following to the `dotspacemacs-additional-packages`:

```emacs-lisp
dotspacemacs-additional-packages '((awqat :location (recipe
                                                         :fetcher github
                                                         :repo "zkry/awqat")))
```
And somewhere in the `dotspacemacs/user-config` function, do `(require 'awqat)`.

**Comment by zkry** [comment]
Thanks! I'm glad you find it useful. What you mentioned about the safety times is definitely a mistake. I'll fix that along with adding documentation for the installation and latitude/longitude.
