### ISSUE TITLE
Incorrect Isha angle in the preset of Umm al-Qura

### ISSUE THREAD

**Issue by abougouffa** [zkry/awqat#7]
Hello, first, I would like to thank you for this package.

I want to bring your attention to the preset of Umm al-Qura University

https://github.com/zkry/awqat/blob/1664c7e0403367ca2713115874d25fdcf661a990/awqat.el#L128-L130

In fact, the angle for Isha is not defined, Umm al-Qura do not use an angle based calculation for Isha. 

Instead, it adds a fixed amount of time to the Maghrib time as follows:
- 90 minutes after Maghrib for all months except Ramadan.
- 120 minutes after Maghrib time during Ramadan.

**Comment by zkry** [comment]
Thanks for bringing this up and working on it! It will definitely be good to have this fixed 👍

**Comment by abougouffa** [comment]
@zkry Thank you for your reply,

I'm glad to contribute to this project!
