### ISSUE TITLE
For some reason, it stopped working. I am getting "Cannot open load file: No such file or directory, awqat"

### ISSUE THREAD

**Issue by AbeEtan** [zkry/awqat#9]
It worked beautifully for a few hours then stopped working all of a sudden.  I get the following error.

`Cannot open load file: No such file or directory, awqat`

**Comment by zkry** [comment]
Just from looking at the error, it seems it could be a problem with the package not existing on your load path. If you execute <kbd>M-x</kbd> eval-expression <kbd>RET</kbd> (require 'awqat) <kbd>RET</kbd> do you get the same error? If so, you may want to make sure that the package directory is in the load path.

```
(add-to-list 'load-path "~/mysubdir/awqat")
```

Definitely let me know if this doesn't work.

**Comment by AbeEtan** [comment]
This is exactly what I have in my init.el file. It worked for a few hours then stopped working. 
```
;;Awqat - Islamic prayer times for Emacs
(add-to-list 'load-path "/home/abe/awqat/awqat.el")
(require 'awqat)
(setq calendar-latitude 21.487301)
(setq calendar-longitude 39.181339)
;;mode line mode to show the remaining time for the next prayer.
(setq awqat-mode-line-format " 🕌 ${prayer} (${hours}h${minutes}m) ")
(awqat-set-preset-muslim-world-league)
(setq awqat-isha-angle -21.0)  
```
![image](https://user-images.githubusercontent.com/85316227/215083591-3bd1bafe-6554-4fb0-afd9-135c439eedbe.png)

As you can see from the image, the package exists in the load path variable. Not sure what is going on to be honest.

**Comment by zkry** [comment]
I think I see the problem. Try changing your add-to-list statement to the following:

```
(add-to-list 'load-path "/home/abe/awqat/")
```

I'm almost positive the load-path variable should be a list of directories so putting a file there wouldn't cause it to be loaded.

**Comment by AbeEtan** [comment]
Thank you so much. A silly mistake on my end. Thank you for your help.
It worked the first time because I had set up with the directory then I changed it because I thought it was incorrect and causing a mistake, apparently not. Ha-ha!

**Comment by zkry** [comment]
awesome! glad it works now. Definitely let me know if you experience any other problems.
